### ISSUE TITLE
automate manual processes in run.sh 

### ISSUE THREAD

**Issue by bendraabdelali** [bendraabdelali/Building-a-Real-time-Dashboard-with-Kafka-Spark-MongoDB-and-Streamlit#2]

**Comment by ysfesr** [comment]
Can you provide more details about this issue?

**Comment by bendraabdelali** [comment]
in the run.sh we have a command that 'is excuted manually we went to autmate the process of excuted those  command

**Comment by ysfesr** [comment]
run.sh is empty !
