### ISSUE TITLE
 Reorganize the files for a dashboard application

### ISSUE THREAD

**Issue by ysfesr** [bendraabdelali/Building-a-Real-time-Dashboard-with-Kafka-Spark-MongoDB-and-Streamlit#5]
Could you please help reorganize the files for the dashboard application?
The current organization is causing some confusion and making it difficult to find things

**Comment by bendraabdelali** [comment]
Okay, I will reorganize the project.

**Comment by bendraabdelali** [comment]
Check now.

**Comment by ysfesr** [comment]
Good job Mr. Abdelali
